### PR TITLE
Feat/login widget

### PR DESCRIPTION
**Pull request by shmbajaj**
# Login Widget

## Preview

https://github.com/One-Click-Auth/auth_frontend/assets/29247011/899e3c17-32a1-441c-9019-6c23cd8e2cd2

## Info
- Didn't added `signin-footer` and parent-card styles, as saved for later (as last commit).
- Using old email-login logic, because parent component business logic requires refactoring.
- Todo's are left purposely will be cleared post doubts clarification.
- Cannot test login flow using email signup was not happening successfully, may be BE issue.

## Open Queries
- What is the plan to switch between email login ui or widgets? (feature-flag 🤔)
- Do `/widget/login` page background-colour change require, as per figma?
- What to show on click on `Privacy Policy and Terms &amp; Conditions.`?

### CODE REVIEW

**Comment by shmbajaj** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shmbajaj** [comment]
recheck

**Comment by moonlightnexus** [comment]
> # Login Widget
> ## Preview
>  41481858-58a2-4fb0-842c-4087fa869634.mp4 
> ## Info
> * Didn't added `signin-footer` and parent-card styles, as saved for later (as last commit).
> * Using old email-login logic, because parent component business logic requires refactoring.
> * Todo's are left purposely will be cleared post doubts clarification.
> * Cannot test login flow using email signup was not happening successfully, may be BE issue.
> 
> ## Open Queries
> * What is the plan to switch between email login ui or widgets? (feature-flag 🤔)
> * Do `/widget/login` page background-colour change require, as per figma?
> * What to show on click on `Privacy Policy and Terms &amp; Conditions.`?

first this one: 
What to show on click on Privacy Policy and Terms &amp; Conditions.?

the first api call in DOM is returning a data

image

the data

{
    "org_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXCJnQUFBQUFCbHM4U3NORFZTQV9BM3E5alkzN29xaXBERXF2Mi1UY0lYbmJtbDhNY2NqNUhwYWMtMklqZERtLXlYdkVHdzVicVNNQTM3blliYlBFNFY0UjBSSDBBeWpHa015TE1Jd2lGbVBOZzBSUXdXSVk4WHNoc2lxUDJOS1owLXNkeGtLSDh5UjlTOGZXZ3pWZWp1V2tNdTJxcHFROGF4aVJ0VVEzckNYakY0OEhrWU81N0lLQTZmU01laVJLZlBtcGt0RUJyVl9aNGtzVGtNN05VeGtvOFlyVlBLejdXSDBTZVRFWUU0a1J5ZC1QdU40WVc4VEJzTnB1VWg5d1N2eHlVdXBDa3pUT0owa29nVkpiV0E2d0dUdHhKN3JZS3N5eXh1Wk0xVFV6UkNKUTJuaS1sUWl6OE8xVlVuNUF6ZFMwNkNzRTA2RGxjejFrbFVIZ1BwdmlLTzlqbDJmYmdadXhFV25sdEoxWFB0OTd3c1o2akljcVdtRzlHUXFOODY4T090YzJRbU1kUjVsVWJPM0JlRTVlWmN1dGFyeUUtX3BfV0MwVWhTdWdqUEhzbUlfVV9zMTBtV2JkZ0tGYldtbjBfZGd0ZlZUNm9DNjlrLW1sQnFhYTc4VXpDQXRqeTVoUzUxczYwam52ajdkckthNnY0U0loMGZ3V2JFZERwQ1NWcGNaUHdoYVFiaExTU2JaWU1UWWwwS3FSa0Q1VmhUczZVbkZ5cWV0ZW5mM2N4X2IyY1JiMGQ5SDc4YzhmYkh3bUVwWXV3MGtCVGhUbXhoRDBMd3FfeWxfQ1IyMVNxTXZfTUt5R0xvbmlmbG5yZS1ycE9Tb1BCdm8xRHY0a1Z1REw4Y0xoZy05TGZZVFNlMGFhR3JBM21ad0Q2alpRLUhqa3I3WWdzVFdPVGZQNXdQb3o3a2k1dXRJakdsaEJ3Z3IwYk1pQkRPZVRBeTlOSnBTTF9nNFZ0a0NERzBQdU44WExsQnZFZWdtM0pkeW5nQUFMSm5RQ2l4Mm1zQzNDdWE4b0Z6NFh5emZPNklGME1SdS1HdFllb0M0Szd6c2F6RjFScmhqUk9HN1pJdVZOSUMtcVdVX0lwVjNxbkxvSEVSVUJRUG5wdVJLaDdnWjVuOUg2RGc0R2FvNW1RanpGRS1tMmpzNVB1OXAwcXR4SHNoR2J3VVFCVUpUVW9MTTZFSF81U1hoTHdaY2pwUWNqZ3RhQ1VRYkoxQlY3bkdMNnVySlFJRWNyYXN6SW1SbjJmRnd1NzFEamJoQUNqR2VCdS1pdDVFLUlmaG4tN0hMVGxZckN6Wk9jazVnMVQxSUlmV3kwOW9VVDNWOG00VlJpVDc4WHJVTWM5RzVsbHN4akRraENEeWhKWWlKTFNuY3F0OXpfX0FTdnBZaHJDaFV0bHFyck1NSWVWX3ZJOXUzaGJmNEpyc09yR05LLWp3RURCYlNGVUdjcVdZSzhteExLQ3BaWVdmZTlQc3ByRHpkTkZkUWxjQVRYSTBNakF6SklvYW1FQW9aVDlyZzRuMmxKeFl0Mks2MjloZVJRMUQwZVVaT2FRT3VqNXBmWHJrd1hLUVRFVEo5SmtudzhnYzFtNmRMUkFxZWdHdHRFdEZQenVjbExCVk9tOF9qX21NajV3RG0wbU1zd2cwMU1ZcGRBTzBRYWlfTGFSeVM3akdQSTQtVXVBblRvbTEwNlFrM181OXdxanQxWXNZMzJwUm9NTUtXMVNWV19WUG5KcDU3Q3lSZ3NYRDFxQm4zRmdXUXlobTJ0UVpJdmJTaFI3NEhHNnZIVHhRLWdSVk9XaGhEdWlOYWdQTmpzbzdnSnFYRjBBX0Q1MjZUMTQ2YXpXcmRBYUEzMEUteEVJM1lGYUxfdnVuM2FMRmJGcEMzLVNuVWkzVHBrd3VZdVcxbHo1bGtVMmJBWWo1YVBkSFpwVlFmS2lJY1Z2SUU5NDdfLUVYSHhRQ0NObk15RGxIdHpsMEdfajFNVUhsWC1PRTZkRGFBXzlpNlRVVlVrWnBOdi1ZQTJiTWF0cGQ0XzZKZ1E1bV9ZQnpvcTVhWHh5MzMzd3o0YTV3MUNvYnJ6UUltbTZZOEpGajRxRlR1aERUcjRqU2R1WUZQdEpuSmZadXBRVFZvSGNOWVBFdU1lcGxFNGE5WnZFaUdlSFpsQTR1M2tvSEpFcUZPU1BTLTltOC1HeFM4Rk9rX3B0b0NUWi1ZMFFkNDVmMGJHRlhLTUpsd3RrTVBHQThQd283Rl9rYXRveDk5aXNHckdTeDJLZFpMd3VabTNqNUxFR0FfbWpxUldhdEF3WnlzSmdPZ2NCTm1sVzNPVGxlR25uVkg4em1XY2Z0d2ZIS2lKWHQzSDNfeXhDZ21sbVIwMDNDaHhFMTdBOVhXeTNmbzBDa3p4TzhaWEh1OXN2Z19ObVZYX29fa0s5d0pvTHZMcnQ1aWt4X0JyNXpDdjhJalFvUHFuYzJCaUFBX29sVXU4cmk2Q0t2OG9EY0pIV0FvanpZMld5X0d6RlNQTnhPWnFUTHY5NDFfLUhGSGxhaDFxS1BOb0JiRzFCZzlFMlc1am84S0pYaXJoTkdxR3BIbTMwR2N1SndlWUhUTVpYV1gzdU05S0xxRWszRl91Tk45bHdHclVyeHVoZWMxWWtralczWUhIc3c1NThWVmVpWFVsa040UUlGUG9zTkZtY1otcVBZRnBUTHRIaWcyamQwS3JmajZiNjMtdkRXR2IycV9lNkVTVjhyZTdzcGxuUlEwem15R1ZOUkRmc3Vnbm5RaVc1aXNBNHFfblNrcWFPMFoydlFtdEdudEdIbzQ1R0o4LTEycWowcDItYk9TRlBGU0k1alZ6M0w0dFBOaVloV1l6Rzc4OUlwLTNkVldGQ1JZUWh6S2xXVEl6Mmphc3dVUC1Yd3VRbHJPWTliMUN3eFZ2RThlU01LQ2RYYktBVHBDNkhyWGJrMmROenBjaVp1X3VmMkV1bHFLS0xFYlB3c3puSXVMSmhkS2RNbmdEZ3ItMkFsU0FZR1BWd2w0bFpDb2VZUkY0a2k1eFNtcVQwZVhuTWZwUWlVcnNYbTV0cW1xbnZPbmI1X3JYLVRtdjRVd2hBbXlpa0Z6X2taalhOSUUyTnA3bFAwelpXb2d6ZzQ0cUZCSzNoNGVTcnU4R2NMRTZDTXZYdV9sam9WcGgzdEprTzVaTHd1Y0lGb2g0REJ1dW9VRUJfVjZEZnRsTDFnTFQ4ZjdyVmdpZTZ5Ql9iNzI5NWFEUTlMeHVqbjlnU1pGb0htdDByNTNQd1YyNUJVTHA0SzhCcERLaWF5TFk4dVhXRWc2OXlJUHhpLWtCUDVrNWNnY05ubUVwWEVEM2FVR1N1MkZaYkNYOFpqWWhnNjhvS2J2QTA4LW1hM2xKaDY4c1JPS0FDZ2o3WHV0X002UHFiYTJWN09vNDJqcE5FRV9DNmltVVhkX0MweEFDU19wRmpVVWlUbGRMeFhpQTBJeUlyVWJ4bTNQdFpyWktaX3dBSEZxeDFVYnpnblRXT3RlaU1vbW83WnhqZ3otNUs2TURuQmswZWljZVZfM2hUWS1qVWduaHd2MVNwa3JObXVzTjhpTWJlbFplcFk4Q0VPTnY2azVQY2dqNTI5SUNSckpqWWJPakJ5cG5jYVlUeG5wanVMdWtla0FORktzWVJRWEk3eWVfZVZNNGl4V2JJMlVTUHEyWWZQNW9YdUpob1luaENWNUlybzJyRUpSakJ0TVl3bm5neUNEODBBQnV2ZDhZaUMxUHVIUS1NajNnYzNfcGpjcW9LdjRiYTJBd2diNU9MNkFIQ093aWEyVWRqX0ExWl9KaEJ1Tk9WTHVsS1VibXlMSjA5M2xWTUtHMXZpXzNtel84cEU4S2dVREpsdWFmc2R2amNCSTEzemk3SnltSV9LLWVXcmN0Qk9NSDVzTUFGbmFBMm1IU3FiVUdhUnUzRHlHa2lrRVhlYjBsZ0toUVJUSDRoanljLWcya0JXaF9QekFKbDUtcVNnUzVKWUhHejdUWUtMeDZybmJSVjBKdWRXYTFjR3UxZ3dzaEI4ZVA5UXVTNlQ2eUtaaEVkOWY1Tmp4a2xpeEpmb1FrN3NPM1o3aDVVRUtSeVJlWGx4UHN0NDhEQk9ZeVFrWFA4SXJPNmJNdkpsYnBna0FSaXo4eWg1NnlSNmFPVlU4VHhZZkRhNmJ3TVpCSzlmdlo4Rlc2U0VFM3BFQXBJSW51RUlEaXM3UzRQNmMydmE1Q0Z4d0N0eVhwTTlsa1JCUU1sd3RFTnFNRWwyYXRIakU5T2FKOThRTVo2NEh0akh5bTY4bkpGZFgxLXFHX1ZUZWMwVU9pZ1d0QXR4M2JTYzZ6Nmk4WUhBVG1KbXpnM2pxaUVqMnozVGhqeDlfZWFNZUc0X0pnPT1cIiJ9.JymyHwb7_QOYXxDpZFdqvWSzHr9L-nh-efJtwehyjK8",
    "data": {
        "breach_pass_det": false,
        "m2m": false,
        "secret_m": false,
        "key_m": false,
        "card_m": false,
        "fa2": false,
        "strict_mfa": false,
        "consent": false,
        "booking": false,
        "ref": false,
        "phone_fa2": false,
        "phone_passwordless": false,
        "callbacks": false,
        "passwordless": true,
        "custom_email": false,
        "DDoS": false,
        "bot_det": true,
        "brute_force": false,
        "email_val": false,
        "social_sign": false,
        "SSO": [],
        "social": {
            "microsoft": {},
            "google": {},
            "github": {},
            "discord": {},
            "figma": {}
        },
        "widget": {
            "name": "Flitch-Pay",
            "logo_url": "https://openauthx.s3.ap-south-1.amazonaws.com/a2a0fa4704ffa7e0d42a9deca4facc05_Ellipse%20285.png",
            "font": "inter",
            "greeting": "Continue to Log in to Flitch-Pay",
            "input_border": {
                "radius": 13.0,
                "color": "#caa9ff"
            },
            "widget_border": {
                "radius": 13.0,
                "color": "#00FFA3",
                "width": 0.0
            },
            "button": {
                "radius": 13,
                "bc": "#471B8F",
                "width": 0
            },
            "color0": "#471B8F",
            "color1": "#DC1FFF",
            "color2": "#DC1FFF",
            "color3": "#31006b",
            "color4": "#000000",
            "color5": "#000000",
            "color6": "#e3d5ff",
            "color7": "#e3d5ff",
            "color8": "#661aff",
            "color9": "#ffffff",
            "color10": "#000000",
            "color11": "#535353",
            "color12": "#000000",
            "social": {},
            "tnc": null,
            "pp": null,
            "redirect_url": "https://money.flitchcoin.com/"
        },
        "callback_url": "",
        "decor_img": "https://openauthx.s3.ap-south-1.amazonaws.com/e2529b922dc69c508dc1d6fc1d5d2756_iPhone%2014%20Pro%20-%2014%20%284%29.png"
    }
}

these values will provide terms and conditions and privacy policy respectively 
 "tnc": null,
 "pp": null,

**Comment by shmbajaj** [comment]
> > # Login Widget
> > ## Preview
> > 41481858-58a2-4fb0-842c-4087fa869634.mp4
> > ## Info
> > 
> > * Didn't added `signin-footer` and parent-card styles, as saved for later (as last commit).
> > * Using old email-login logic, because parent component business logic requires refactoring.
> > * Todo's are left purposely will be cleared post doubts clarification.
> > * Cannot test login flow using email signup was not happening successfully, may be BE issue.
> > 
> > ## Open Queries
> > 
> > * What is the plan to switch between email login ui or widgets? (feature-flag 🤔)
> > * Do `/widget/login` page background-colour change require, as per figma?
> > * What to show on click on `Privacy Policy and Terms &amp; Conditions.`?
> 
> first this one: What to show on click on Privacy Policy and Terms & Conditions.?
> 
> the first api call in DOM is returning a data
> 
> image
> 
> the data
> 
> { "org_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiXCJnQUFBQUFCbHM4U3NORFZTQV9BM3E5alkzN29xaXBERXF2Mi1UY0lYbmJtbDhNY2NqNUhwYWMtMklqZERtLXlYdkVHdzVicVNNQTM3blliYlBFNFY0UjBSSDBBeWpHa015TE1Jd2lGbVBOZzBSUXdXSVk4WHNoc2lxUDJOS1owLXNkeGtLSDh5UjlTOGZXZ3pWZWp1V2tNdTJxcHFROGF4aVJ0VVEzckNYakY0OEhrWU81N0lLQTZmU01laVJLZlBtcGt0RUJyVl9aNGtzVGtNN05VeGtvOFlyVlBLejdXSDBTZVRFWUU0a1J5ZC1QdU40WVc4VEJzTnB1VWg5d1N2eHlVdXBDa3pUT0owa29nVkpiV0E2d0dUdHhKN3JZS3N5eXh1Wk0xVFV6UkNKUTJuaS1sUWl6OE8xVlVuNUF6ZFMwNkNzRTA2RGxjejFrbFVIZ1BwdmlLTzlqbDJmYmdadXhFV25sdEoxWFB0OTd3c1o2akljcVdtRzlHUXFOODY4T090YzJRbU1kUjVsVWJPM0JlRTVlWmN1dGFyeUUtX3BfV0MwVWhTdWdqUEhzbUlfVV9zMTBtV2JkZ0tGYldtbjBfZGd0ZlZUNm9DNjlrLW1sQnFhYTc4VXpDQXRqeTVoUzUxczYwam52ajdkckthNnY0U0loMGZ3V2JFZERwQ1NWcGNaUHdoYVFiaExTU2JaWU1UWWwwS3FSa0Q1VmhUczZVbkZ5cWV0ZW5mM2N4X2IyY1JiMGQ5SDc4YzhmYkh3bUVwWXV3MGtCVGhUbXhoRDBMd3FfeWxfQ1IyMVNxTXZfTUt5R0xvbmlmbG5yZS1ycE9Tb1BCdm8xRHY0a1Z1REw4Y0xoZy05TGZZVFNlMGFhR3JBM21ad0Q2alpRLUhqa3I3WWdzVFdPVGZQNXdQb3o3a2k1dXRJakdsaEJ3Z3IwYk1pQkRPZVRBeTlOSnBTTF9nNFZ0a0NERzBQdU44WExsQnZFZWdtM0pkeW5nQUFMSm5RQ2l4Mm1zQzNDdWE4b0Z6NFh5emZPNklGME1SdS1HdFllb0M0Szd6c2F6RjFScmhqUk9HN1pJdVZOSUMtcVdVX0lwVjNxbkxvSEVSVUJRUG5wdVJLaDdnWjVuOUg2RGc0R2FvNW1RanpGRS1tMmpzNVB1OXAwcXR4SHNoR2J3VVFCVUpUVW9MTTZFSF81U1hoTHdaY2pwUWNqZ3RhQ1VRYkoxQlY3bkdMNnVySlFJRWNyYXN6SW1SbjJmRnd1NzFEamJoQUNqR2VCdS1pdDVFLUlmaG4tN0hMVGxZckN6Wk9jazVnMVQxSUlmV3kwOW9VVDNWOG00VlJpVDc4WHJVTWM5RzVsbHN4akRraENEeWhKWWlKTFNuY3F0OXpfX0FTdnBZaHJDaFV0bHFyck1NSWVWX3ZJOXUzaGJmNEpyc09yR05LLWp3RURCYlNGVUdjcVdZSzhteExLQ3BaWVdmZTlQc3ByRHpkTkZkUWxjQVRYSTBNakF6SklvYW1FQW9aVDlyZzRuMmxKeFl0Mks2MjloZVJRMUQwZVVaT2FRT3VqNXBmWHJrd1hLUVRFVEo5SmtudzhnYzFtNmRMUkFxZWdHdHRFdEZQenVjbExCVk9tOF9qX21NajV3RG0wbU1zd2cwMU1ZcGRBTzBRYWlfTGFSeVM3akdQSTQtVXVBblRvbTEwNlFrM181OXdxanQxWXNZMzJwUm9NTUtXMVNWV19WUG5KcDU3Q3lSZ3NYRDFxQm4zRmdXUXlobTJ0UVpJdmJTaFI3NEhHNnZIVHhRLWdSVk9XaGhEdWlOYWdQTmpzbzdnSnFYRjBBX0Q1MjZUMTQ2YXpXcmRBYUEzMEUteEVJM1lGYUxfdnVuM2FMRmJGcEMzLVNuVWkzVHBrd3VZdVcxbHo1bGtVMmJBWWo1YVBkSFpwVlFmS2lJY1Z2SUU5NDdfLUVYSHhRQ0NObk15RGxIdHpsMEdfajFNVUhsWC1PRTZkRGFBXzlpNlRVVlVrWnBOdi1ZQTJiTWF0cGQ0XzZKZ1E1bV9ZQnpvcTVhWHh5MzMzd3o0YTV3MUNvYnJ6UUltbTZZOEpGajRxRlR1aERUcjRqU2R1WUZQdEpuSmZadXBRVFZvSGNOWVBFdU1lcGxFNGE5WnZFaUdlSFpsQTR1M2tvSEpFcUZPU1BTLTltOC1HeFM4Rk9rX3B0b0NUWi1ZMFFkNDVmMGJHRlhLTUpsd3RrTVBHQThQd283Rl9rYXRveDk5aXNHckdTeDJLZFpMd3VabTNqNUxFR0FfbWpxUldhdEF3WnlzSmdPZ2NCTm1sVzNPVGxlR25uVkg4em1XY2Z0d2ZIS2lKWHQzSDNfeXhDZ21sbVIwMDNDaHhFMTdBOVhXeTNmbzBDa3p4TzhaWEh1OXN2Z19ObVZYX29fa0s5d0pvTHZMcnQ1aWt4X0JyNXpDdjhJalFvUHFuYzJCaUFBX29sVXU4cmk2Q0t2OG9EY0pIV0FvanpZMld5X0d6RlNQTnhPWnFUTHY5NDFfLUhGSGxhaDFxS1BOb0JiRzFCZzlFMlc1am84S0pYaXJoTkdxR3BIbTMwR2N1SndlWUhUTVpYV1gzdU05S0xxRWszRl91Tk45bHdHclVyeHVoZWMxWWtralczWUhIc3c1NThWVmVpWFVsa040UUlGUG9zTkZtY1otcVBZRnBUTHRIaWcyamQwS3JmajZiNjMtdkRXR2IycV9lNkVTVjhyZTdzcGxuUlEwem15R1ZOUkRmc3Vnbm5RaVc1aXNBNHFfblNrcWFPMFoydlFtdEdudEdIbzQ1R0o4LTEycWowcDItYk9TRlBGU0k1alZ6M0w0dFBOaVloV1l6Rzc4OUlwLTNkVldGQ1JZUWh6S2xXVEl6Mmphc3dVUC1Yd3VRbHJPWTliMUN3eFZ2RThlU01LQ2RYYktBVHBDNkhyWGJrMmROenBjaVp1X3VmMkV1bHFLS0xFYlB3c3puSXVMSmhkS2RNbmdEZ3ItMkFsU0FZR1BWd2w0bFpDb2VZUkY0a2k1eFNtcVQwZVhuTWZwUWlVcnNYbTV0cW1xbnZPbmI1X3JYLVRtdjRVd2hBbXlpa0Z6X2taalhOSUUyTnA3bFAwelpXb2d6ZzQ0cUZCSzNoNGVTcnU4R2NMRTZDTXZYdV9sam9WcGgzdEprTzVaTHd1Y0lGb2g0REJ1dW9VRUJfVjZEZnRsTDFnTFQ4ZjdyVmdpZTZ5Ql9iNzI5NWFEUTlMeHVqbjlnU1pGb0htdDByNTNQd1YyNUJVTHA0SzhCcERLaWF5TFk4dVhXRWc2OXlJUHhpLWtCUDVrNWNnY05ubUVwWEVEM2FVR1N1MkZaYkNYOFpqWWhnNjhvS2J2QTA4LW1hM2xKaDY4c1JPS0FDZ2o3WHV0X002UHFiYTJWN09vNDJqcE5FRV9DNmltVVhkX0MweEFDU19wRmpVVWlUbGRMeFhpQTBJeUlyVWJ4bTNQdFpyWktaX3dBSEZxeDFVYnpnblRXT3RlaU1vbW83WnhqZ3otNUs2TURuQmswZWljZVZfM2hUWS1qVWduaHd2MVNwa3JObXVzTjhpTWJlbFplcFk4Q0VPTnY2azVQY2dqNTI5SUNSckpqWWJPakJ5cG5jYVlUeG5wanVMdWtla0FORktzWVJRWEk3eWVfZVZNNGl4V2JJMlVTUHEyWWZQNW9YdUpob1luaENWNUlybzJyRUpSakJ0TVl3bm5neUNEODBBQnV2ZDhZaUMxUHVIUS1NajNnYzNfcGpjcW9LdjRiYTJBd2diNU9MNkFIQ093aWEyVWRqX0ExWl9KaEJ1Tk9WTHVsS1VibXlMSjA5M2xWTUtHMXZpXzNtel84cEU4S2dVREpsdWFmc2R2amNCSTEzemk3SnltSV9LLWVXcmN0Qk9NSDVzTUFGbmFBMm1IU3FiVUdhUnUzRHlHa2lrRVhlYjBsZ0toUVJUSDRoanljLWcya0JXaF9QekFKbDUtcVNnUzVKWUhHejdUWUtMeDZybmJSVjBKdWRXYTFjR3UxZ3dzaEI4ZVA5UXVTNlQ2eUtaaEVkOWY1Tmp4a2xpeEpmb1FrN3NPM1o3aDVVRUtSeVJlWGx4UHN0NDhEQk9ZeVFrWFA4SXJPNmJNdkpsYnBna0FSaXo4eWg1NnlSNmFPVlU4VHhZZkRhNmJ3TVpCSzlmdlo4Rlc2U0VFM3BFQXBJSW51RUlEaXM3UzRQNmMydmE1Q0Z4d0N0eVhwTTlsa1JCUU1sd3RFTnFNRWwyYXRIakU5T2FKOThRTVo2NEh0akh5bTY4bkpGZFgxLXFHX1ZUZWMwVU9pZ1d0QXR4M2JTYzZ6Nmk4WUhBVG1KbXpnM2pxaUVqMnozVGhqeDlfZWFNZUc0X0pnPT1cIiJ9.JymyHwb7_QOYXxDpZFdqvWSzHr9L-nh-efJtwehyjK8", "data": { "breach_pass_det": false, "m2m": false, "secret_m": false, "key_m": false, "card_m": false, "fa2": false, "strict_mfa": false, "consent": false, "booking": false, "ref": false, "phone_fa2": false, "phone_passwordless": false, "callbacks": false, "passwordless": true, "custom_email": false, "DDoS": false, "bot_det": true, "brute_force": false, "email_val": false, "social_sign": false, "SSO": [], "social": { "microsoft": {}, "google": {}, "github": {}, "discord": {}, "figma": {} }, "widget": { "name": "Flitch-Pay", "logo_url": "https://openauthx.s3.ap-south-1.amazonaws.com/a2a0fa4704ffa7e0d42a9deca4facc05_Ellipse%20285.png", "font": "inter", "greeting": "Continue to Log in to Flitch-Pay", "input_border": { "radius": 13.0, "color": "#caa9ff" }, "widget_border": { "radius": 13.0, "color": "#00FFA3", "width": 0.0 }, "button": { "radius": 13, "bc": "#471B8F", "width": 0 }, "color0": "#471B8F", "color1": "#DC1FFF", "color2": "#DC1FFF", "color3": "#31006b", "color4": "#000000", "color5": "#000000", "color6": "#e3d5ff", "color7": "#e3d5ff", "color8": "#661aff", "color9": "#ffffff", "color10": "#000000", "color11": "#535353", "color12": "#000000", "social": {}, "tnc": null, "pp": null, "redirect_url": "https://money.flitchcoin.com/" }, "callback_url": "", "decor_img": "https://openauthx.s3.ap-south-1.amazonaws.com/e2529b922dc69c508dc1d6fc1d5d2756_iPhone%2014%20Pro%20-%2014%20%284%29.png" } }
> 
> these values will provide terms and conditions and privacy policy respectively "tnc": null, "pp": null,

@moonlightnexus Not correct, so leaving it with a comment over the code.

**Comment by shmbajaj** [comment]
Removed All Todos:
- use widget button or change widget button styles, because previous components are still using widgetbutton.
-  change socialbutton to accept string content as child 
- implement social logins

**Pull request merged**
